### ISSUE TITLE
Unable to process messages >255 bytes

### ISSUE THREAD

**Issue by saumilsdk** [jsaak/mqtt-sn-gateway#1]
UDPInterface - Not a valid Mqtts message. Field "Length" (1) in the received data packet is less than 2 . The packet cannot be processed.

**Comment by jsaak** [comment]
it does work, you should double check your packet

**Comment by saumilsdk** [comment]
@jsaak I checked and found that it doesn't work. These code needs some changes in UDPInterface to handle that.

**Comment by jsaak** [comment]
Give us some proof.

**Comment by saumilsdk** [comment]
Here is the proof
https://github.com/saumilsdk/eclipse-paho-mqtt-sn-udp-client/commit/99d473cfe2e20607917dbba46f136370fd44d335

**Comment by jsaak** [comment]
We are talking about two different things. I was talking about the gateway, you the udp-client. As the readme states, i have not looked at the clients. And I have no intentions to support them at all.

**Comment by saumilsdk** [comment]
Yes you are right. I was talking about client and not the gateway. Sorry for confusion.
